=== Network Security Groups
In this reference architecture, four network security groups are created. The purpose of the network security groups are to
 restrict traffic from outside of the _VNet_ to servers inside of the _VNet_. The network security groups
 also are used to restrict server to server communications inside the _VNet_. Network security groups provide
 an extra layer of security similar to a firewall. In the event a port is opened on an instance,
 the security group will not allow the communication to the port unless explicitly stated in a network security group.
 These settings are in each node types json file, located in https://github.com/openshift/openshift-ansible-contrib/tree/master/reference-architecture/azure-ansible/ (like `master.json` for master instances)

==== Bastion Security Group
The Bastion network security group allows _SSH_. Any connectivity via _SSH_ to the master, application or infrastructure nodes must go through the bastion host.

==== Master Security Group
The Master network security group allows _SSH_ from the bastion, and communications to other masters.
The Master network security group allows inbound access on port 8443 from the internet to the virtual network.
The traffic is then allowed to be forwarded to the master instances.

==== Router/Infra Security Group
The Router/Infra network security group allows inbound access on port 80 and 443. If the applications running on the OpenShift cluster are using different ports this can be adjusted as needed.

// vim: set syntax=asciidoc:
