=== Registry
*{ocp}* can build container images from source code, deploy them, and
manage their lifecycle. To enable this it is required to deploy the
https://docs.openshift.com/container-platform/3.5/architecture/infrastructure_components/image_registry.html[Integrated OpenShift Container Platform Registry]

The registry stores container images and metadata. For production environment,
persistent storage is recommended to be used by the registry, otherwise any images
built or pushed into the registry would disappear if the pod were to restart.

The registry is scaled to 3 pods/instances to allow for HA, and load balancing. The default
load balancing settings use the source ip address to enforce session stickiness. Failure of a
pod may result in a pull or push operation to fail, but the operation may be restarted. The failed registry
pod will be automatically restarted.

Using the installation methods described in this document the registry is
deployed using `Azure Blob Storage`, an *{ma}* service that provides object storage.
In order to use `Azure Blob Storage` the registry configuration has been extended.
The procedure used is detailed in the https://docs.openshift.com/container-platform/3.5/install_config/registry/extended_registry_configuration.html#docker-registry-configuration-reference-storage[OpenShift] and https://docs.docker.com/registry/storage-drivers/azure/[Docker] documentation, and it is to modify the registry `deploymentconfig` to add the `Azure Blob Storage` service details as:

[subs=+quotes]
----
$ *oc env dc docker-registry -e REGISTRY_STORAGE=azure -e REGISTRY_STORAGE_AZURE_ACCOUNTNAME=<azure_storage_account_name> -e REGISTRY_STORAGE_AZURE_ACCOUNTKEY=<azure_storage_account_key> -e REGISTRY_STORAGE_AZURE_CONTAINER=registry*
----

This will be done automatically as part of the installation by the scripts provided in the git repository.

NOTE: For more information about the *{ma}* Blob Storage, see: https://azure.microsoft.com/en-us/services/storage/blobs/

// vim: set syntax=asciidoc:
