[[refarch_details]]

=== Generated Inventory
Ansible relies on inventory files and variables to perform playbook runs.
As part of the reference architecture provided Ansible playbooks,
the inventory is created during the boot of the bastion host. The `Azure Resource Manager` templates (`ARM`) passes parameters via a script extension to `RHEL` on the bastion. On the bastion host
a bastion.sh script generates the inventory file in `/etc/ansible/hosts`.

[[app-listing]]
.Dynamic Inventory Script within bastion.sh
[source,bash]
----
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
debug_level=2
console_port=8443
docker_udev_workaround=True
openshift_node_debug_level="{{ node_debug_level | default(debug_level, true) }}"
openshift_master_debug_level="{{ master_debug_level | default(debug_level, true) }}"
openshift_master_access_token_max_seconds=2419200
openshift_hosted_router_replicas=3
openshift_hosted_registry_replicas=1
openshift_master_api_port="{{ console_port }}"
openshift_master_console_port="{{ console_port }}"
openshift_override_hostname_check=true
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
osm_use_cockpit=false
openshift_release=v3.5
openshift_cloudprovider_kind=azure
openshift_node_local_quota_per_fsgroup=512Mi
azure_resource_group=${RESOURCEGROUP}
rhn_pool_id=${RHNPOOLID}
openshift_install_examples=true
deployment_type=openshift-enterprise
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

# default selectors for router and registry services
openshift_router_selector='role=infra'
openshift_registry_selector='role=infra'

# Select default nodes for projects
osm_default_node_selector="role=app"
ansible_become=yes
ansible_ssh_user=${AUSERNAME}
remote_user=${AUSERNAME}

openshift_master_default_subdomain=${WILDCARDNIP}
osm_default_subdomain=${WILDCARDNIP}
openshift_use_dnsmasq=false
openshift_public_hostname=${RESOURCEGROUP}.${FULLDOMAIN}

openshift_master_cluster_method=native
openshift_master_cluster_hostname=${RESOURCEGROUP}.${FULLDOMAIN}
openshift_master_cluster_public_hostname=${RESOURCEGROUP}.${FULLDOMAIN}

[masters]
master1 openshift_hostname=master1 openshift_node_labels="{'role': 'master'}"
master2 openshift_hostname=master2 openshift_node_labels="{'role': 'master'}"
master3 openshift_hostname=master3 openshift_node_labels="{'role': 'master'}"

[etcd]
master1
master2
master3

[nodes]
master1 openshift_hostname=master1 openshift_node_labels="{'role':'master','zone':'default'}" openshift_schedulable=false
master2 openshift_hostname=master2 openshift_node_labels="{'role':'master','zone':'default'}" openshift_schedulable=false
master3 openshift_hostname=master3 openshift_node_labels="{'role':'master','zone':'default'}" openshift_schedulable=false
node[01:${NODECOUNT}] openshift_node_labels="{'role': 'app', 'zone': 'default'}"
infranode1 openshift_hostname=infranode1 openshift_node_labels="{'role': 'infra', 'zone': 'default'}"
infranode2 openshift_hostname=infranode2 openshift_node_labels="{'role': 'infra', 'zone': 'default'}"
infranode3 openshift_hostname=infranode3 openshift_node_labels="{'role': 'infra', 'zone': 'default'}"

[compute]
node[01:${NODECOUNT}] openshift_node_labels="{'role': 'app', 'zone': 'default'}"
----

NOTE: Those are the values chosen for the *{ocp}* installation in this reference architecture, for more information about those parameters and their values, see the  https://docs.openshift.com/container-platform/3.5/install_config/install/advanced_install.html#configuring-ansible[OpenShift documentation]

For the *{ocp}* installation, the `ARM` template collects the
needed parameters, creates the virtual machines, and passes the parameters to the virtual
machines, where a node type specific script in bash will take the parameters and
generate the needed playbooks and automation. During this process each VM is assigned
an ansible tag, that allows the playbooks to address the different node types.

NOTE: For more information about the automation procedures on *{ma}*, see  https://azure.microsoft.com/en-us/blog/automate-linux-vm-customization-tasks-using-customscript-extension/[Azure Linux Automation] blog post
and for more information about the Ansible inventory, see http://docs.ansible.com/ansible/intro_inventory.html[Ansible Host Inventory]

// vim: set syntax=asciidoc:
