=== *{rhocp}* Metrics

*{rhocp}* environments can be enriched by deploying an optional component named *{rhocp} metrics* that collect metrics exposed by the `kubelet` from pods running in the environment and provides the ability to view CPU, memory, and network-based metrics and display the values in the user interface.

NOTE: *{rhocp}* metrics is a required component for the `horizontal pod autoscaling` feature that allows the user to configure autoscaling pods on a certain capacity thresholds. For more information about pod autoscaling, see https://docs.openshift.com/container-platform/3.5/dev_guide/pod_autoscaling.html#req-for-using-hpas[Pod Autoscaling].

*{rhocp}* metrics it is composed by a few pods running on the *{rhocp}* environment:

* Heapster: Heapster scrapes the metrics for CPU, memory and network usage on every pod, then exports them into Hawkular Metrics.
* Hawkular Metrics: A metrics engine which stores the data persistently in a Cassandra database.
* Cassandra: Database where the metrics data is stored.

It is important to understand https://docs.openshift.com/container-platform/3.5/install_config/cluster_metrics.html#capacity-planning-for-openshift-metrics[capacity planning] when deploying metrics into an OpenShift environment regarding that one set of metrics pods (Cassandra/Hawkular/Heapster) is https://docs.openshift.com/container-platform/3.5/scaling_performance/scaling_cluster_metrics.html#cluster-metrics-scaling-openshift-metrics-pods[able to monitor at least 25,000 pods].

*{rhocp}* metrics components can be customized for longer data persistence, pods limits, replicas of individual components, custom certificates, etc.

NOTE: For more information about different customization parameters, see https://docs.openshift.com/container-platform/3.5/install_config/cluster_metrics.html[Enabling Cluster Metrics] documentation.

Within this reference environment, metrics are deployed optionally on the infrastructure nodes depending on the "metrics" parameter of the `ARM template`. When "true" is selected, it deploys one set of metric pods (Cassandra/Hawkular/Heapster) on the infrastructure nodes (to avoid using resources on the application nodes) and uses persistent storage to allow for metrics data to be preserved for 7 days.

==== Horizontal pod Autoscaler

If *{rhocp}* metrics has been deployed the *horizontal pod autoscaler* feature can be used. A horizontal pod autoscaler, defined by a `HorizontalPodAutoscaler` object, specifies how the system should automatically increase or decrease the scale of a replication controller or deployment configuration, based on metrics collected from the pods that belong to that replication controller or deployment configuration.

NOTE: For more information about the pod autoscaling feature, see the  https://docs.openshift.com/container-platform/3.5/dev_guide/pod_autoscaling.html[official documentation]


// vim: set syntax=asciidoc:
