[[AVMI]]

==== Azure VM Images
Azure VM Images provide the required information to launch an instance. In this guide, the the On-Demand Red Hat Enterprise Linux (RHEL)
image in the Azure Gallery is used. The Red Hat RHEL Image carries an additional charge in addition to the base Linux VM price.

NOTE: For more information see https://azure.microsoft.com/en-us/pricing/details/virtual-machines/red-hat[Azure Documentation].

==== Azure VM Sizes

The bastion host size is controlled by the master size
specified in the template. The Infra nodes can be specified separately. Node VM
size is an important parameter for selecting how many containers as well as how big containers
will be. The current default for nodes allocates 28 Gigabytes of memory. This gives
around 26 gigabytes for application usage. If the containers are memory intensive
then it is advised to either increase the node count, or increase the node memory size.
For these applications, choosing a "Standard_D14_v2" will give 112 gigabytes of memory or another VM size with more memory if needed.

Further, all the nodes, have been selected with Microsoft Azure Premium Storage, to
allow the best performance.


// vim: set syntax=asciidoc:
