[[dns]]

=== Microsoft Azure DNS
DNS is an integral part of a successful *{ocp}* environment. *{ma}* provides a DNS-as-a-Service called `Azure DNS`, per Microsoft;
"The Microsoft global network of name servers has the scale and redundancy to ensure ultra-high availability for your domains.
With *{ma}* DNS, you can be sure that your DNS will always be available."

*{ma}* provides the DNS for public zone, as well as internal host resolution. These are configured automatically
during the execution of the reference architecture scripts.

NOTE: For more information see https://docs.microsoft.com/en-us/azure/dns/[Azure DNS documentation]

==== Public Zone
When the reference architecture is deployed, *{ma}* supplied domains are used. The domains consists of:
<hostname>.<region>.cloudapp.azure.com.

For each *{ocp}* deployment on *{ma}*, there are three created domain names:

* <resourcegroup>.<region>.cloudapp.azure.com - The API and *{ocp}* web console load balancer
* <resourcegroup>b.<region>.cloudapp.azure.com - The bastion host for ssh access
* <wildcardzone>.<region>.cloudapp.azure.com - The DNS of the applications load balancer

IMPORTANT: Due to the current *{ma}* limitations on creating subdomains and wildcards, the *nip.io* service is used for the application load balancer. For more information about current *{ma}* limitations with subdomains, check the following link https://feedback.azure.com/forums/216843-virtual-machines/suggestions/6119382-subdomain-cloudapp-net-etc-rather-than-having-a[subdomain cloudapp.net rather than having a global namespace]

NOTE: In order to have a proper wildcard DNS entry with a proper subdomain like `\*.apps.mycompany.com`, it is recommended to create a wildcard A record externally with your `DNS` domain provider and configure it to the applications load balancer IP like:
`*.apps.mycompany.com.` `300 IN  A 192.168.133.2`
To reflect those modifications in *{ocp}*, modify the `routingConfig.subdomain` parameter in the `/etc/origin/master/master-config.yaml` file in all the masters and restart the `atomic-openshift-master` service, or modify the ansible hosts file and rerun the installation.

==== Internal resolution
This reference architecture uses https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances#azure-provided-name-resolution[Azure-provided name resolution] mechanism which:

* creates an internal subdomain per `resource group` like `fesj5eh111uernc5jfpnxi33kh.dx.internal.cloudapp.net`
* creates an A `DNS` record on that internal subdomain of every instance deployed in that `resource group`
* configures the proper resolution in the `/etc/resolv.conf` file on every VM

Using this, instances can be reached using just the VM shortname:

[subs=+quotes]
----
$ *cat /etc/resolv.conf*
# Generated by NetworkManager
search fesj5eh114uebnc5jfpnxi33kh.dx.internal.cloudapp.net
nameserver 168.63.129.16

$ *nslookup master1*
Server:		168.63.129.16
Address:	168.63.129.16#53

Name:	master1.fesj5eh114uebnc5jfpnxi33kh.dx.internal.cloudapp.net
Address: 10.0.0.5
----

// vim: set syntax=asciidoc:
