==== *{ma}* Load Balancer
*{ma}* provides an `Azure Load Balancer` (`ALB`) service which enables distribution of traffic
across multiple instances in the *{ma}* cloud.  Two `ALB` are used in the deployment of
*{ocp}*:

* To expose a single entry point for the *{ocp}* API and console
* To expose a single entry point for applications exposed to outside using the *{ocp}* routers

.*{ma}* Load Balancer
|====
^|ALB |DNS name ^| Assigned Instances ^| Port

| External load balancer | <resourcegroupname>.<region>.cloudapp.azure.com | master1-3 | 8443
| Router load balancer |  <wildcardzone>.<region>.cloudapp.azure.com | infra-nodes1-3 | 80 and 443
|====

There are clear advantages to doing this:

* Keeps applications highly available.
* It is secure, it works with the *{ma}* cloud to leverage features such as separation of public/private cloud traffic
and health monitoring.

`Azure Load Balancer` itself is fully-fault tolerant, and designed for implementing native azure highly-available applications.

NOTE: For more information see the https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-overview[Azure Load Balancer documentation]

`Azure Load Balancer` implements parts of the <<Routing-Layer>>.

// vim: set syntax=asciidoc:
