=== Microsoft Azure DNS
`DNS` is an integral part of a successful OpenShift Compute Platform deployment/environment. `Azure` has a `DNS` service, per Microsoft;
"The Microsoft global network of name servers has the scale and redundancy to ensure ultra-high availability for your domains.
With Azure DNS, you can be sure that your DNS will always be available."

Azure provides the DNS for public zone, as well as internal host resolution. These are configured automatically
during the execution of the reference architecture scripts.
For more information see https://azure.microsoft.com/en-us/services/dns/

==== Public Zone
When the reference architecture is deployed, `Azure` supplied domains are used. The domains consists of:
_hostname.{region}.cloudapp.azure.com_. For example, in the `southeastasia` zone, the full domain of the bastion
host would be _bastion.southeastasia.cloudapp.azure.com_.

For each OpenShift Cluster on Azure, there are three created domain names:

* _{resroucegroup}.{region}.cloudapp.azure.com_ - The API and OpenShift Console Load Balancer
* _{resourcegroup}b.{region}.cloudapp.azure.com_ - The bastion host for ssh access
* _{wildcardzone}.{region}.cloudapp.azure.com_ - the DNS/IP of the Application Load Balancer.

In initial deployment, a nip dns name is generated to point to the Application load balancer,
to allow immediate usage of the deployed openshift. A Wildcard CNAME should be created to another name of
choice.

// vim: set syntax=asciidoc:
