[[AVMI]]

==== *{ma}* VM Images
`Azure Virtual Machines Images` provide different virtual machine images to launch instances. In this reference architecture, the `On-Demand` *Red Hat Enterprise Linux* (`RHEL`) image in the *Azure Marketplace* is used.

IMPORTANT: The *Red Hat Enterprise Linux* image carries an additional charge in addition to the base `Linux VM` price. For more information on *{ma}* pricing for Red Hat images see https://azure.microsoft.com/en-us/pricing/details/virtual-machines/red-hat[Azure Documentation].

==== *{ma}* VM Sizes
*{ma}* offers https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes[different VM sizes] that can be used to deploy the *{ocp}* environment.
Further, all the nodes, have been selected with `premium storage`, to allow the best performance.

NOTE: The sizes provided in this reference architecture are a guide but it is advised to see the
https://docs.openshift.com/container-platform/3.5/install_config/install/planning.html#sizing[OpenShift Container Platform 3 Sizing Considerations]
for more information

The VM sizes are specified as parameters in the template file `reference-architecture/azure-ansible/azuredeploy.json` and the following table shows the specific parameter of each VM type and its default value:

.Default VM sizes
|====
^|Type ^|Parameter ^|Default size

| Bastion | `bastionVMSize` | `Standard_DS1_v2`
| Masters | `masterVMSize` | `Standard_DS4_v2`
| Infrastructure nodes | `infranodeVMSize` | `Standard_DS4_v2`
| Application nodes | `nodeVMSize` | `Standard_DS4_v2`
|====

Application node VM size is an important parameter for selecting how many containers as well as how big containers
will be. The current default value for application nodes size allocates 8 CPU cores and 28 Gigabytes of memory for each VM.
If the containers are memory intensive then it is advised to either increase the node count, or increase the node memory size.
For these applications, choosing a `Standard_D14_v2` size will give 112 Gigabytes of memory or another VM size with more memory if needed.

// vim: set syntax=asciidoc:
