== Conclusion

Red Hat solutions involving the *OpenShift Container Platform* are created to deliver a production-ready foundation that simplifies the deployment process, shares the latest best practices, and provides a stable highly available environment on which to run production applications.

This reference architecture covered the following topics:

* A completely provisioned infrastructure in Azure public cloud
* OpenShift router and registry deployed in dedicated infrastructure nodes
* Native integration with Azure services as:
** _Azure Load Balancer_ for load balancing the API and console and for the applications running in OpenShift
** _Azure VHD_ storage for persistent storage of container images
** _Azure Premium Storage_ for docker storage on each node
** _Azure Blob Storage_ for registry to increase scaling
** _Azure Availability Zones_ to increase reliability
* Creation of applications
* Validating the environment
* Testing failover

For any questions or concerns, please email refarch-feedback@redhat.com and ensure to visit the http://red.ht/1IEYbQT[Red Hat Reference Architecture page to find about all of our Red Hat solution offerings.

// vim: set syntax=asciidoc:
