== Conclusion

Red Hat solutions involving the *{ocp}* are created to deliver a production-ready foundation that simplifies the deployment process, shares the latest best practices, and provides a stable highly available environment on which to run production applications.

This reference architecture covered the following topics:

* A completely provisioned infrastructure in *{ma}* public cloud
* *{ocp}* router and registry deployed in dedicated infrastructure nodes
* Native integration with *{ma}* services as:
** `Azure Load Balancer` for load balancing the API and console and for the applications running in *{ocp}*
** `Azure VHD` storage for persistent storage of container images
** `Azure Premium Storage` for docker storage on each node
** `Azure Blob Storage` for registry to increase scaling
** `Azure Availability Zones` to increase reliability
* Creation of applications
* Validating the environment
* Testing failover

For any questions or concerns, please email refarch-feedback@redhat.com and ensure to visit the http://red.ht/1IEYbQT[Red Hat Reference Architecture page to find about all of our Red Hat solution offerings.

// vim: set syntax=asciidoc:
